[package]
name = "fountain_converter"
version = "0.1.0"
authors = ["Simon Ganz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3"
unicode_categories = "0.1.1"
regex = "1.3.9"
lazy_static = "1.4.0"

[[bench]]
name = "my_benchmark"
harness = false