[package]
name = "jumpcut"
version = "0.2.0"
authors = ["Simon Ganz"]
edition = "2018"

[lib]
name = "jumpcut"
path = "src/lib.rs"

[[bin]]
name = "jumpcut"
path = "src/bin/jumpcut.rs"

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"
structopt = "0.3"
unicode-segmentation = "1.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"
unicode_categories = "0.1.1"
pretty_assertions = "0.6.1"

[[bench]]
name = "my_benchmark"
harness = false