[package]
name = "jumpcut"
version = "0.5.4"
edition = "2021"

[dependencies]
regex = "1.5.4"
lazy_static = "1.4.0"
unicode-segmentation = "1.8.0"
serde = { version = "1.0.133", features = ["derive"] }
handlebars = "4.1.6"
serde_json = "1.0.74"

[dev-dependencies]
criterion = "0.3.5"
unicode_categories = "0.1.1"
pretty_assertions = "1.0.0"

[[bench]]
name = "jumpcut_benchmarks"
harness = false
