[package]
name = "jumpcut"
version = "0.5.2"
edition = "2021"

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"
unicode-segmentation = "1.7.1"
serde = { version = "1.0", features = ["derive"] }
handlebars = "3.5.3"
serde_json = "1.0.73"

[dev-dependencies]
criterion = "0.3"
unicode_categories = "0.1.1"
pretty_assertions = "0.6.1"

[[bench]]
name = "jumpcut_benchmarks"
harness = false
