[package]
name = "jumpcut_cli"
version = "0.6.0"
authors = ["Simon Ganz"]
edition = "2021"

[[bin]]
name = "jumpcut"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
jumpcut = { path = "../jumpcut" }
clap = { version = "4.5.7", features = ["derive"] }
