[package]
name = "jumpcut-cli"
version = "0.5.0"
authors = ["Simon Ganz"]
edition = "2021"

[[bin]]
name = "jumpcut"
path = "src/main.rs"

[dependencies]
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jumpcut = { path = "../jumpcut" }
